services:

  be_python:
    build: ./be-python
    ports: 
      - "8001:8001"
    volumes:
      - ./be-python:/app
    networks:
      - app-network
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8001", "--reload"]

networks:
  app-network:
    driver: bridge