services:

  be_python:
    build: ./be-python
    ports: 
      - "8001:8001"
    networks:
      - app-network
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8001"]

networks:
  app-network:
    driver: bridge