services:
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus
    networks:
      - app-network

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--web.enable-remote-write-receiver"
    networks:
      - app-network

  k6:
    image: grafana/k6:latest
    volumes:
      - ./k6:/k6
    entrypoint: ["k6"]
    # profiles: ["tests"]
    environment:
      - K6_PROMETHEUS_RW_SERVER_URL=http://prometheus:9090/api/v1/write
    depends_on:
      - prometheus
    networks:
      - app-network
  
  be_python:
    build:
      context: .
      dockerfile: be-python/Dockerfile
    ports: 
      - "8001:8001"
    networks:
      - app-network
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8001"]

  be_node:
    build:
      context: .
      dockerfile: be-node/Dockerfile
    ports:
      - "8002:8002"
    networks:
      - app-network
    command: ["node", "index.js"]

networks:
  app-network:
    driver: bridge