{
 "title": "CPU Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "rate(k6_http_reqs[1m])",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "k6_http_reqs_total" } },
   "targets": [
    { "expr": "rate(k6_http_reqs[1m])" }
   ]
  },
  {
   "title": "Avg Request Duration (Node & Python)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "megabytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"be_node\"} / 1024 / 1024",
     "legendFormat": "Node.js avg"
    },
    {
     "expr": "process_resident_memory_bytes{job=\"be_python\"} / 1024 / 1024",
     "legendFormat": "Python"
    }
   ]
  },
  {
   "title": "CPU vs Virtual Users",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[1m]) * 100",
     "legendFormat": "CPU (%) {{job}}"
    },
    { "expr": "avg(k6_vus)", "legendFormat": "Virtual Users" }
   ]
  }
 ]
}