{
 "title": "HTTP Request Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "rate(k6_http_reqs[1m])",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "k6_http_reqs_total" } },
   "targets": [
    { "expr": "rate(k6_http_reqs[1m])" }
   ]
  },
  {
   "title": "Total Http requests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Requests" } },
   "targets": [
    { "expr": "sum(k6_http_reqs_total)" }
   ]
  },
  {
   "title": "P99",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_req_duration_seconds_bucket[1m])) by (le))"
    }
   ]
  },
  {
   "title": "rate(process_cpu_seconds_total[1m]) * 100",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[1m]) * 100"
    }
   ]
  },
  {
   "title": "Requests per Endpoint (last 5m)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(node_http_requests_total[5m])",
     "legendFormat": "Node: {{endpoint}}"
    },
    {
     "expr": "rate(python_http_requests_total[5m])",
     "legendFormat": "Python: {{endpoint}}"
    }
   ]
  },
  {
   "title": "CPU vs Virtual Users",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[1m]) * 100",
     "legendFormat": "CPU (%)"
    },
    { "expr": "k6_vus", "legendFormat": "Virtual Users" }
   ]
  }
 ]
}