global:
  scrape_interval: 5s

scrape_configs:

  - job_name: 'be_python'
    metrics_path: /metrics
    static_configs:
      - targets: ['be_python:8001']

  - job_name: 'be_node'
    metrics_path: /metrics
    static_configs:
      - targets: ['be_node:8002']
