global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']  # Self-scrape

  - job_name: 'be_python'
    metrics_path: /metrics
    static_configs:
      - targets: ['be_python:8001']
