global:
  scrape_interval: 5s

scrape_configs:

  - job_name: 'fastapi'
    metrics_path: /metrics
    static_configs:
      - targets: ['fastapi:8001']

  - job_name: 'express'
    metrics_path: /metrics
    static_configs:
      - targets: ['express:8002']
